### ISSUE TITLE
search Term is not defined....

### ISSUE THREAD

**Issue by Rohangith1** [Rohangith1/uixcont#2]
TypeError: Cannot read properties of undefined (reading 'searchTerm')
    at Navbar.js:19:1
    at useSelector.ts:182:1
    at memoizedSelector (use-sync-external-store-with-selector.development.js:78:1)
    at getSnapshotWithSelector (use-sync-external-store-with-selector.development.js:133:1)
    at mountSyncExternalStore (react-dom.development.js:15980:1)
    at Object.useSyncExternalStore (react-dom.development.js:16908:1)
    at useSyncExternalStore (react.development.js:1676:1)
    at useSyncExternalStoreWithSelector (use-sync-external-store-with-selector.development.js:144:1)
    at useSelector2 (useSelector.ts:249:1)
    at Navbar (Navbar.js:19:1)

**Comment by Rohangith1** [comment]
this error drive me 5-6 yours only i left "u" word ... finally figured out
